version: '3'

services:
  # API
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn src.api:app --host 0.0.0.0
    volumes:
      - ./data:/app/data  # Mount for SQLite database to host directory
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.local

  # Proxy (Nginx)
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api

  # Redis (Cache / Broker / Vector Index / Stream)
  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379

  # Minio (File Storage)
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: CHANGEME
      MINIO_ROOT_PASSWORD: CHANGEME
    volumes:
      - ~/minio/data:/data
      - ~/minio/config:/root/.minio
    command: server /data --console-address ":9001"