name: Run Tests

on: [push]

env:
  PYTHON_VERSION: 3.9
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: $PYTHON_VERSION
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt

    - name: Run tests
      run: |
        export OPENAI_API_KEY=$OPENAI_API_KEY
        echo ">> Running all test cases"
        python3 -m pytest -s tests
